version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/default/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"

  - package-ecosystem: "bundler"
    directory: "/default/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
