permalink: /blog/:year/:month/:title
name: Asa's Website
url: "https://a01sa01to.com"
author: Asa
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
exclude:
  - "src"

defaults:
-
  scope:
    path: "err/**"
  values:
    sitemap: false

autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts:
      - 'blog_autopage.html'
    enabled: true
    permalink: 'blog/tags/:tag'
    title: '「:tag」の記事一覧'

pagination:
  enabled: true
  per_page: 15
  title: ':title(Page:num)'
  sort_reverse: true