permalink: /:year/:month/:day
name: Asa's Blog
url: "https://blog.a01sa01to.com"
author: Asa
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
defaults:
-
  scope:
    path: "err/**"
  values:
    sitemap: false

autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts:
      - 'blog_autopage.html'
    enabled: true
    permalink: 'tags/:tag'
    title: '「:tag」の記事一覧'

pagination:
  enabled: true
  per_page: 15
  title: ':title(Page:num)'
  sort_reverse: true