name: Default Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Get gems cache directory path
        id: gems-cache-dir-path
        run: echo "::set-output name=dir::$(gems cache dir)"
      - name: Cache deps
        uses: actions/cache@v2
        with:
          path: ${{ steps.gems-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install deps
        run: bundle install
        working-directory: ./default
      - name: Build
        run: jekyll build
        working-directory: ./default
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./default/_site
          publish_branch: def_deploy