name: Opendata Build

on:
  push:
    branches:
      - main
    paths:
      - 'kss-new/**'

jobs:
  build:
    name: Copy and Deploy
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./kss-new
          publish_branch: kss-new_deploy