name: Default Build

on:
  push:
    branches:
      - main
    paths:
      - 'default/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          ref: main
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
      - name: Cache deps
        uses: actions/cache@v2.1.6
        with:
          path: ./default/vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('./default/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Prepare bundler
        run: |
          gem install bundler
          bundle config path vendor/bundle
        working-directory: ./default
      - name: Install deps
        run: bundle install
        working-directory: ./default
      - name: Build
        run: bundle exec jekyll build
        working-directory: ./default
      - name: Compress Images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./default/_site
          publish_branch: def_deploy
