name: Data Update

on: workflow_dispatch

jobs:
  push_master:
    name: Push to master branch
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Add remote
        run: git remote add origin https://github.com/a01sa01to/my-website.git
      - name: Fetch
        run: git fetch origin
